django_heroku/urls.py
import django_heroku_webpage
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('django_heroku_webpage.urls')),
]

django_heroku_webpage/urls.py
from django.urls import path
from . import views

app_name = 'django_heroku_webpage'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

django_heroku_webpage/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

django_heroku_webpage/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widget = {'text': forms.Textarea(attrs={'cols': 80})}

django_heroku_webpage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    return render(request, 'django_heroku_webpage/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'django_heroku_webpage/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'django_heroku_webpage/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            form.save()
            return redirect('django_heroku_webpage:topics')

    context = {'form': form}
    return render(request, 'django_heroku_webpage/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('django_heroku_webpage:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'django_heroku_webpage/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instace=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('django_heroku_webpage:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'django_heroku_webpage/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('django_heroku_webpage:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

django_heroku_webpage/templates/django_heroku_webpage/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Topics and Notes</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'django_heroku_webpage:index' %}">Home Page</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav_link" href="{% url 'django_heroku_webpage:topics' %}">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

django_heroku_webpage/templates/django_heroku_webpage/edit_entry.html
{% extends "django_heroku_webpage/base.html" %}
{% block content %}
    <h1><a href="{% url 'django_heroku_webpage:topic' topic.id %}">{{ topic }}</a></h1>
    <h2>Edit entry:</h2>
    <form action="{% url 'django_heroku_webpage:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

django_heroku_webpage/templates/django_heroku_webpage/index.html
{% extends "django_heroku_webpage/base.html" %}
{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Track your Notes</h1>
    <p class="lead">Make your own Notes, and keep a list of th for the main Topic. Enjoy!</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

django_heroku_webpage/templates/django_heroku_webpage/new_entry.html
{% extends "django_heroku_webpage/base.html" %}
{% block content %}
    <h1><a href="{% url 'django_heroku_webpage:topic' topic.id %}">{{ topic }}</a></h1>
    <h2>Add new entry:</h2>
    <form action="{% url 'django_heroku_webpage:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

django_heroku_webpage/templates/django_heroku_webpage/new_topic.html
{% extends "django_heroku_webpage/base.html" %}
{% block content %}
    <h1>Add a new Topic</h1>
    <form action="{% url 'django_heroku_webpage:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Topic</button>
    </form>
{% endblock content %}

django_heroku_webpage/templates/django_heroku_webpage/topic.html
{% extends "django_heroku_webpage/base.html" %}
{% block page-header %}
    <h1> Topic: {{ topic }} </h1>
{% endblock page-header %}
{% block content %}
    <p>
        <a href="{% url 'django_heroku_webpage:new_entry' topic.id %}">Add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'django_heroku_webpage:edit_entry' topic.id %}">Edit entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>No entries for this topic have been added.</p>
    {% endfor %}
{% endblock content %}

django_heroku_webpage/templates/django_heroku_webpage/topics.html
{% extends "django_heroku_webpage/base.html" %}
{% block page-header %}
    <h1> Topics </h1>
{% endblock page-header %}
{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'django_heroku_webpage:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>
                <h3>No topics have been added.</h3>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}